### ISSUE TITLE
Android 手机9.0系统，希望您适配下9.0系统，我这边部分已经自己适配

### ISSUE THREAD

**Issue by EsZhangHome** [ChanWong21/PonyMusic#59]
2019-02-21 15:25:12.353 10315-10315/me.wcy.music E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.wcy.music, PID: 10315
    java.lang.NullPointerException: Attempt to invoke virtual method 'void me.wcy.music.fragment.LocalMusicFragment.onRestoreInstanceState(android.os.Bundle)' on a null object reference
        at me.wcy.music.activity.MusicActivity.lambda$onRestoreInstanceState$1(MusicActivity.java:244)
        at me.wcy.music.activity.-$$Lambda$MusicActivity$lstZRa7EYJWoFB17qucMW9l0jMY.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by EsZhangHome** [comment]
报上面的错误，不知是咋回事了
